version: '3.8'

services:
  backend:
    image: nokeshk/hms-backend:latest
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/hms_db?createDatabaseIfNotExist=true
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - JWT_SECRET=mySuperSecretKeyThatIsAtLeast32CharactersLongForJWT
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: nokeshk/hms-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hms_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge